language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
  - ~/.cache
notifications:
  email: false
node_js:
- "8"
os:
- linux
addons:
  chrome: stable
  hosts:
    - localhost
  apt:
    sources:
    - sourceline: "deb https://dl.yarnpkg.com/debian/ stable main"
      key_url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages:
    - yarn
    - libgconf-2-4
install:
- yarn config list
- yarn
script:
- ./tasks/ci-script.sh
after_success:
- ./tasks/deploy.sh
- if $RELEASE; then yarn run semantic-release; fi
after_failure:
- "./cypress/support/s3-artifact-upload.sh"
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    S3SCREENSHOT: true
    S3COMPARISON: true
    S3VIDEO: true
